{
  "name": "await-catch",
  "version": "1.6.7",
  "description": "Async await wrapper for easy error handling",
  "main": "./lib/index.js",
  "scripts": {
    "build": "NODE_ENV=\"production\" babel src -d lib",
    "prepublish": "npm run build",
    "test": "mocha --compilers js:babel-core/register"
  },
  "keywords": [
    "async-await",
    "async",
    "await",
    "try-catch",
    "try",
    "catch",
    "es6",
    "promise"
  ],
  "bugs": {
    "url": "https://github.com/bufface/await-catch/issues",
    "email": "bufface@gmail.com"
  },
  "homepage": "https://github.com/bufface/await-catch",
  "repository": {
    "type": "git",
    "url": "https://github.com/bufface/await-catch"
  },
  "author": "Cristian Buffa <bufface@gmail.com> (https://github.com/bufface)",
  "license": "MIT",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "chai": "^4.1.2",
    "mocha": "^5.0.1"
  },
  "dependencies": {
    "babel-polyfill": "^6.26.0"
  }
}
